#MySQL database: (Using MariaDB server type)
hostname: 'localhost'
port: '3306' # use 3308 if not working
database: 'ABMCJudge' #automatically created if it does not exist
user: 'root'
password: ''

console:
  error: "This command can only be ran by a player!"